services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "53333:53333"
    container_name: server_test
    volumes:
      #- .:/app
      - data:/app/data
      - logs:/app/logs

volumes:
  data:
  logs: